### ISSUE TITLE
Update package in apm

### ISSUE THREAD

**Issue by rpowelll** [GijsGoudzwaard/base16-ocean-dark#7]
While this theme has been update to support the 1.0 API, you haven't actually pushed those changes up to apm. You should just be able to do an `apm publish minor` from within the repo's directory to push a new release.

**Comment by robbschiller** [comment]
Hey @rpowelll! Thanks for the heads up. You know I've neglected this package a bit. I'm not actively using Atom anymore (drank the vim juice). Would you be interested in taking over the package?
